# Generated by Django 5.0.6 on 2024-05-12 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('endurance', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('describe', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Conveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mine', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('series_number', models.CharField(max_length=200)),
                ('manufacture_date', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('manual', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Splice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('when_made', models.DateField(auto_now_add=True)),
                ('when_modify', models.DateField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('angle', models.IntegerField(blank=True, null=True)),
                ('angle_length', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('slevel_op', models.IntegerField(blank=True, null=True)),
                ('slevel_mag', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('belt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conveyors', to='connectors.conveyor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presses', to='connectors.press')),
            ],
            options={
                'ordering': ('when_made',),
            },
        ),
    ]
