# Generated by Django 5.0.6 on 2024-05-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splice',
            name='slug',
        ),
        migrations.AddField(
            model_name='splice',
            name='conveyor_machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conveyors', to='connectors.conveyor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='splice',
            name='belt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='connectors.belt'),
        ),
    ]
