# Generated by Django 5.0.6 on 2024-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_remove_belt_slug_remove_conveyor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='splices/%Y/%m/%d/'),
        ),
    ]
