# Generated by Django 5.0.6 on 2024-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_alter_splice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splice',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
