# Generated by Django 5.0.6 on 2024-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_alter_splice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='manual',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
